### ISSUE TITLE
`strstream` is deprecated and will be removed from the standard

### ISSUE THREAD

**Issue by KOLANICH** [jamesderlin/dropt#10]
>`#include <strstream>`

https://en.cppreference.com/w/cpp/io/strstream
>strstream has been deprecated since C++98, std::stringstream and boost::iostreams::array are the recommended replacements

**Comment by jamesderlin** [comment]
Where do you see `#include <strstream>`?

**Comment by jamesderlin** [comment]
I don't see any use of a deprecated `strstream` header in dropt, so I don't understand what this issue is talking about.  If you still think there's a problem that needs to be addressed, feel free to reopen this with more specific details.

**Comment by KOLANICH** [comment]
I'm sorry. It was in my code wrapping `dropt` (and so situated in `Dropt.cpp`).
